name: gempak_compare
channels:
  - conda-forge
dependencies:
  - python=3
  - cartopy
  - numpy
  - matplotlib
  - siphon
  - xarray
  - pint
  - jupyterlab
  - pip
  - pip:
     - git+https://github.com/Unidata/MetPy.git@refs/pull/1353/head
